import os, re, sys, json
import psycopg
mode = sys.argv[1]
assert mode in ('small', 'work')
prefix = os.environ['PERSONAL_PREFIX']
assert re.fullmatch(r'[a-z][a-z_]{1,62}', prefix)
r, b, c, n = (50,100,200,300) if mode == 'small' else (3000,10000,30000,50000)
with psycopg.connect(os.environ['DATABASE_URL']) as conn:
    conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{prefix}"')
    conn.execute(f'SET search_path TO "{prefix}"')
    conn.execute('DROP TABLE IF EXISTS loans,copies,books,readers CASCADE')
    conn.execute('CREATE TABLE readers(id int PRIMARY KEY,name text NOT NULL)')
    conn.execute('CREATE TABLE books(id int PRIMARY KEY,title text NOT NULL,cover bytea NOT NULL)')
    conn.execute('CREATE TABLE copies(id int PRIMARY KEY,book_id int NOT NULL REFERENCES books(id))')
    conn.execute('''CREATE TABLE loans(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      reader_id int NOT NULL REFERENCES readers(id),copy_id int NOT NULL REFERENCES copies(id),
      issued_on date NOT NULL,due_on date NOT NULL,returned_on date,
      CHECK(due_on>=issued_on),CHECK(returned_on IS NULL OR returned_on>=issued_on))''')
    conn.execute("INSERT INTO readers SELECT i,'Читатель '||i FROM generate_series(1,%s) i",(r,))
    conn.execute("INSERT INTO books SELECT i,'Книга '||i,decode('89504e470d0a1a0a0000000d4948445200000001000000010804000000b51c0c020000000b4944415478da6364f80f00010501012718e3660000000049454e44ae426082','hex') FROM generate_series(1,%s) i",(b,))
    conn.execute('INSERT INTO copies SELECT i,1+(i-1) %% %s FROM generate_series(1,%s) i',(b,c))
    # Historical loans never overlap. The final 10% are active on distinct copies.
    active=n//10
    conn.execute('''INSERT INTO loans(id,reader_id,copy_id,issued_on,due_on,returned_on)
      SELECT i,1+(i-1) %% %s,1+(i-1) %% %s,
      CASE WHEN i<=%s THEN DATE '2020-01-01'+((i-1)/%s)*30 ELSE DATE '2026-09-01' END,
      CASE WHEN i<=%s THEN DATE '2020-01-15'+((i-1)/%s)*30 ELSE DATE '2026-09-15'+(i %% 40)::int END,
      CASE WHEN i<=%s THEN DATE '2020-01-12'+((i-1)/%s)*30 ELSE NULL END
      FROM generate_series(1,%s) i''',(r,c,n-active,c,n-active,c,n-active,c,n))
    conn.execute("SELECT setval(pg_get_serial_sequence('loans','id'),%s)",(n,))
    conn.execute('ANALYZE')
    counts={t:conn.execute('SELECT count(*) FROM '+t).fetchone()[0] for t in ('readers','books','copies','loans')}
    print(json.dumps({'mode':mode,'prefix':prefix,'counts':counts},ensure_ascii=False))
